version: "3.9"
services:
  hardhat:
    build:
      dockerfile: ./dockerfiles/hardhat.Dockerfile
    ports:
      - "8545:8545"
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=bei-ke-box
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "database"]
      interval: 5s
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./dockerfiles/app.Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
      # For IPFS
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8000:8000"
    image: t3-app
    depends_on:
      database:
        condition: service_healthy